### ISSUE TITLE
Ethernet2 shield

### ISSUE THREAD

**Issue by remco1271** [andresarmento/modbus-arduino#17]
The modbusIp won't work with the ethernet2 shield.
http://www.arduino.org/products/shields/arduino-ethernet-shield-2
I chanced the library from Ethernet to Ethernet2.
I can compile the program.
It is only possible to ping the device for a few seconds and then it lose the connection to the Ethernet.

**Comment by wvengen** [comment]
I'm seeing this as well, I'm afraid it requires the introduction of a new class. Will probably have a go at it somewhere in the coming weeks.

**Comment by wvengen** [comment]
I've added support for the Ethernet 2 at https://github.com/wvengen/modbus-arduino and verified that I can use it to communicate using IP (TCP) and UDP.
