### ISSUE TITLE
Master mode eta?

### ISSUE THREAD

**Issue by shacal** [andresarmento/modbus-arduino#5]

**Comment by Smeedy** [comment]
Looks very promising! Please give an ETA on the Master. Let us know how we can help.

**Comment by shacal** [comment]
Dead project?

**Comment by wvengen** [comment]
Here's a quick method I'm using to send Hreg write packets (no handling of responses though):
https://github.com/wvengen/netswarm-arduino/blob/bd7b173dd9b3ac256a664cb90685bee5d1115a3e/NetSwarm.cpp#L137
